 

name: SonarCloud Analysis

 

on:

  push:

    branches:

      - main  # Change 'main' to your default branch name

 

jobs:

  sonarcloud:

    runs-on: ubuntu-latest

 

    steps:

      - name: Checkout repository

        uses: actions/checkout@v2

 

      - name: Set up JDK 11

        uses: actions/setup-java@v2

        with:

          java-version: '11'

 

      - name: Run SonarCloud analysis

        uses: sonarsource/sonarcloud-github-action@master

        with:

          sonar_login: ${{ secrets.SONAR_TOKEN }}

          project_base_dir: InvestingPlots/Challenge  # Change this if your code is in a subdirectory
